[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "curbsides"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11.0,<4"
ipykernel = ">=6.29.5,<7"
pytorch = ">=2.5.1,<3"
cuda = ">=12.6.2,<13"
torchvision = ">=0.20.1,<0.21"
pandas = ">=2.2.3,<3"
pyarrow = ">=18.0.0,<19"
opencv = ">=4.10.0,<5"
numpy = ">=2.1.3,<3"
tqdm = ">=4.67.0,<5"
tabulate = ">=0.9.0,<0.10"
transformers = ">=4.46.2,<5"
lightning = ">=2.4.0,<3"
tensorboard = ">=2.18.0,<3"
nbdime = ">=4.0.2,<5"

[system-requirements]
cuda = "12"

[pypi-dependencies]
torch-tb-profiler = ">=0.4.3, <0.5"
