[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "curbsides"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.0,<4"
ipykernel = ">=6.29.5,<7"
pytorch = ">=2.5.1,<3"
torchvision = ">=0.20.1,<0.21"
